services:
  postgres:
    image: postgres:16-alpine
    container_name: task_management_db
    environment:
      - POSTGRES_USER=task_management
      - POSTGRES_PASSWORD=task_management
      - POSTGRES_DB=task_management
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local