version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: task_management_db
    environment:
      - POSTGRES_USER=task_management
      - POSTGRES_PASSWORD=task_management
      - POSTGRES_DB=task_management
    ports:
      - 5423:5432
    volumes:
      - postgres_data

volumes:
  postgres_data:
    driver: local